### ISSUE TITLE
censored tweet causes an exception

### ISSUE THREAD

**Issue by moraxy** [ShinNoNoir/twitterwebsearch#5]
If the search results happen to include a censored tweet (e.g. [648188210074513412](https://twitter.com/FlashScoreAT/status/648188210074513412)) an exception gets thrown

```
Traceback (most recent call last):
  File "quickstart.py", line 23, in <module>
    main()
  File "quickstart.py", line 13, in main
    tweets = list(tweets) # convert generator into list
  File "twitterwebsearch/twitterwebsearch/searcher.py", line 64, in search
    for tweet in download_tweets(search=query):
  File "twitterwebsearch/twitterwebsearch/searcher.py", line 53, in download_tweets
    for tweet in parse_search_results(response_dict['items_html'].encode('utf8')):
  File "twitterwebsearch/twitterwebsearch/parser.py", line 68, in parse_search_results
    tweet = parse_tweet_tag(tag)
  File "twitterwebsearch/twitterwebsearch/parser.py", line 24, in parse_tweet_tag
    lang = tweet_body_tag['lang']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

because [`parse_tweet_tag`](https://github.com/ShinNoNoir/twitterwebsearch/blob/519735f1b45d6cd29c65f8417be153bf510f4335/twitterwebsearch/parser.py#L20-L22) in `parser.py` is looking for an element with the `tweet-text` class, which censored tweets apparently don't have.

Regular tweet:

```
<p class="TweetTextSize js-tweet-text tweet-text" data-aria-label-part="0" lang="de">foo</p>
```

Censored tweet:

```
<p class="js-tweet-text">This Tweet from @FlashScoreAT has been withheld in response to a report from the copyright holder. <a href="https://support.twitter.com/articles/15795" target="_blank">Learn more</a>
</p>
```

**Comment by ShinNoNoir** [comment]
Thanks for the report. I'll look into the issue this afternoon. I guess it's best to just ignore censored tweets and drop them silently.

**Comment by ShinNoNoir** [comment]
Fixed in https://github.com/ShinNoNoir/twitterwebsearch/pull/6.
